<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors [
        <!ELEMENT authors (author)*>
        <!ELEMENT author (account, awards*, books*, firstName, id, lastName)>
        <!ELEMENT account (id, password, userName)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT userName (#PCDATA)>
        <!ELEMENT awards (id, title, years)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT years (#PCDATA)>
        <!ELEMENT books (id, name, years)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        ]>
<authors>
    <author>
        <account>
            <id>2</id>
            <password>Password1</password>
            <userName>Username1</userName>
        </account>
        <awards>
            <id>3</id>
            <title>Award1</title>
            <years>2008</years>
        </awards>
        <awards>
            <id>4</id>
            <title>Award2</title>
            <years>2010</years>
        </awards>
        <books>
            <id>5</id>
            <name>Book1</name>
            <years>2005</years>
        </books>
        <books>
            <id>6</id>
            <name>Book2</name>
            <years>2006</years>
        </books>
        <firstName>Name1</firstName>
        <id>1</id>
        <lastName>LastName1</lastName>
    </author>
    <author>
        <account>
            <id>8</id>
            <password>Password2</password>
            <userName>Username2</userName>
        </account>
        <awards>
            <id>9</id>
            <title>Award1</title>
            <years>2008</years>
        </awards>
        <awards>
            <id>10</id>
            <title>Award2</title>
            <years>2010</years>
        </awards>
        <books>
            <id>11</id>
            <name>Book1</name>
            <years>2005</years>
        </books>
        <books>
            <id>12</id>
            <name>Book2</name>
            <years>2006</years>
        </books>
        <firstName>Name2</firstName>
        <id>7</id>
        <lastName>LastName2</lastName>
    </author>
</authors>
